Fixed sound list padding and border style
amilajack/freesound-player pull request #103
Opened 2020-10-17 21:48 UTC by akshara-sun

closes #52 
To-do: 

- [ ] fix top and bottom border styles

- [ ] add icons

2020-10-17 22:41 UTC, amilajack requested changes

2020-10-17 22:41 UTC, amilajack commented on src/styles.css
> +/* .playlist {
We need to remove all comments before merging

2020-10-21 03:57 UTC, amilajack commented
The soundlist needs to have a border around each sound in the sound list

## Implementation
<img width="767" alt="Screen Shot 2020-10-20 at 8 56 17 PM" src="https://user-
images.githubusercontent.com/6374832/96671482-b57cdf00-1316-11eb-8a0c-3a6807c649c9.png">
## Design
<img width="441" alt="Screen Shot 2020-10-20 at 8 55 51 PM" src="https://user-images.githubusercontent.com/6374832/96671475-b0b82b00-1316-11eb-9476-0a222cad6893.png">

2020-10-21 03:57 UTC, amilajack requested changes
The soundlist needs to have a border around each sound in the sound list

## Implementation

<img width="550" alt="Screen Shot 2020-10-20 at 8 57 30 PM" src="https://user-images.githubusercontent.com/6374832/96671548-df360600-1316-11eb-9ee0-d0024942cbef.png">

## Design

<img width="441" alt="Screen Shot 2020-10-20 at 8 55 51 PM" src="https://user-images.githubusercontent.com/6374832/96671475-b0b82b00-1316-11eb-9476-0a222cad6893.png">

2020-10-21 04:05 UTC, akshara-sun commented
@amilajack 

**Thanks for catching that mishap with the border color in dark mode. I've got that part working (as you can see below) except now the top border is a problem. Working on it now, will keep you posted.**

![image](https://user-images.githubusercontent.com/49100882/96671899-cb3ed400-1317-11eb-86e2-0d12c4ca2f24.png)

2020-10-21 05:39 UTC, akshara-sun commented
closes #52 

Current Sound List UI:
- Default (Light Mode):
![image](https://user-images.githubusercontent.com/49100882/96677668-f1b73c00-1324-11eb-8fcd-729a65b978f8.png)

- Dark Mode:
![image](https://user-images.githubusercontent.com/49100882/96677690-fb40a400-1324-11eb-91aa-b25cfb23dba0.png)

2020-10-21 06:51 UTC, akshara-sun commented
I just realized the current styles might potentially pose problems to the design of our home page if and only if we decide to showcase a sound list of sorts on it. Maybe we can talk about this in our Saturday hack - just a thought.

@amilajack @hamirmahal

2020-10-21 15:37 UTC, amilajack approved these changes
Looks good to me! Nice job 🎉

2020-10-21 15:38 UTC, merged

2020-10-21 17:54 UTC, hamirmahal commented
The sound list interface looks awesome, in both themes. Nice job!

2020-10-21 17:56 UTC, hamirmahal commented
Also, I really appreciate the screenshots posted here for quick reference. It allows people to instantly see the results of changes from this pull request, without having to click on any additional links, which is really, really convenient. Thanks!