Sound title and Description redesigned
amilajack/freesound-player pull request #87
Opened 2020-10-03 04:48 UTC by akshara-sun

I am still working on the login, search, explore, and feature buttons but for now, I have made progress on the redesign of the sound title as well as the description sections. 

closes #51

2020-10-04 22:53 UTC, amilajack reviewed
I like how you're using multiple commits to keep track of the changes. That makes it easy to see what was changed 💯

2020-10-07 04:34 UTC, amilajack commented
You have some merge conflicts because Hamir's changes just got merged. You can click the "resolve conflicts" button to fix this.

2020-10-07 06:13 UTC, akshara-sun commented
@amilajack for sure, I'll take care of those merge conflicts! Thanks!

2020-10-09 03:00 UTC, amilajack requested changes

2020-10-09 03:00 UTC, amilajack commented on src/styles.css
> +/* .bg-default {
Why comment this?

2020-10-09 03:00 UTC, amilajack commented on src/styles.css
> +/*
Why comment this?

2020-10-09 04:41 UTC, merged